/**
 * @file types.ts
 * @description Single import point for all shared TypeScript types across the
 * Sovereign-AMM frontend. All interfaces are defined here; mock modules and
 * store slices import from this file to avoid circular dependency issues.
 *
 * Design: interfaces live here, implementations live in lib/mock/* and lib/store.ts.
 */

// ---------------------------------------------------------------------------
// Order Book types
// (used by lib/mock/orderbook.ts and all chart/panel components)
// ---------------------------------------------------------------------------

/**
 * A single price level in the L2 order book.
 *
 * @property px  - Price in ₹/kWh
 * @property sz  - Size (quantity) in kWh
 */
export interface Level {
  /** Price in ₹/kWh. */
  px: number;
  /** Size (quantity) in kWh. */
  sz: number;
}

/**
 * A snapshot of the L2 limit order book, containing 12 bid levels and 12 ask
 * levels generated by the GLFT market-making engine.
 *
 * Invariants:
 *  - `bids` is sorted by `px` descending (best bid first)
 *  - `asks` is sorted by `px` ascending  (best ask first)
 *  - `seq` increments monotonically on each call to `stepBook`
 *
 * @property bids - 12 bid levels, descending price
 * @property asks - 12 ask levels, ascending price
 * @property seq  - Monotone sequence counter; incremented by `stepBook`
 */
export interface OrderBook {
  /** 12 bid levels sorted by price descending. */
  bids: Level[];
  /** 12 ask levels sorted by price ascending. */
  asks: Level[];
  /** Monotone sequence counter, incremented on every `stepBook` call. */
  seq: number;
}

/**
 * A single time-and-sales trade record appended to the rolling 50-entry
 * trade tape in the market slice.
 *
 * @property id   - Deterministic trade ID derived from `book.seq`
 * @property ts   - Wall-clock timestamp in Unix milliseconds (Date.now())
 * @property side - Aggressor side: `'buy'` when OBI > 0, `'sell'` otherwise
 * @property px   - Execution price (micro-price at the tick) in ₹/kWh
 * @property sz   - Trade size in kWh
 */
export interface Trade {
  /** Deterministic trade ID, e.g. `"t-42"`. */
  id: string;
  /** Unix millisecond timestamp from `Date.now()`. */
  ts: number;
  /** Aggressor side: `'buy'` when OBI > 0, `'sell'` otherwise. */
  side: 'buy' | 'sell';
  /** Execution price in ₹/kWh (micro-price at tick time). */
  px: number;
  /** Trade size in kWh. */
  sz: number;
}

// ---------------------------------------------------------------------------
// Timeseries types
// (used by lib/mock/timeseries.ts and PriceStateChart, ParameterCard)
// ---------------------------------------------------------------------------

/**
 * One historical data point produced by `generateTimeseries()`.
 * 240 points are generated at module load time with 100 ms spacing.
 *
 * @property t     - Unix millisecond timestamp
 * @property price - Micro-price in ₹/kWh (Ornstein-Uhlenbeck process, μ=4.85)
 * @property soc   - State of Charge in percent [18, 92]
 * @property cDeg  - Rainflow marginal wear cost in ₹/kWh, clamped to [0.001, 0.08]
 */
export interface TimeseriesPoint {
  /** Unix millisecond timestamp; points are spaced 100 ms apart. */
  t: number;
  /**
   * Micro-price in ₹/kWh.
   * Follows an Ornstein-Uhlenbeck process: θ=0.7, μ=4.85, σ=0.06, dt=0.1.
   */
  price: number;
  /**
   * Battery state of charge in percent.
   * Bounded to [18, 92]; negatively correlated to price deviations from μ.
   */
  soc: number;
  /**
   * Rainflow marginal degradation cost in ₹/kWh.
   * C_deg = C_cap / (2 · N_cycles(d) · E_nom · η)
   * Rises on SoC reversals > 4%, decays 3 %/tick otherwise.
   * Clamped to [0.001, 0.08].
   */
  cDeg: number;
}

// ---------------------------------------------------------------------------
// Grid / power-flow types
// (used by lib/mock/grid.ts, GridTopologySVG, LmpPanel, InjectionOverride)
// ---------------------------------------------------------------------------

/**
 * A bus (node) in the 7-bus microgrid topology.
 *
 * @property id          - Unique identifier, e.g. `"BUS-01"`
 * @property label       - Human-readable label shown in the topology SVG
 * @property x           - SVG x-coordinate in a 600×400 viewBox
 * @property y           - SVG y-coordinate in a 600×400 viewBox
 * @property lmp         - Locational Marginal Price in ₹/kWh
 * @property injectionMW - Net power injection in MW (positive = generation, negative = load)
 * @property type        - Asset class of the bus
 */
export interface Bus {
  /** Unique bus identifier, e.g. `"BUS-01"`. */
  id: string;
  /** Human-readable label displayed in the topology SVG. */
  label: string;
  /** SVG x-coordinate within a 600×400 viewBox. */
  x: number;
  /** SVG y-coordinate within a 600×400 viewBox. */
  y: number;
  /** Locational Marginal Price in ₹/kWh. */
  lmp: number;
  /** Net power injection in MW. Positive = generation; negative = load. */
  injectionMW: number;
  /** Asset class of the bus. */
  type: 'solar' | 'load' | 'storage' | 'slack';
}

/**
 * A transmission line (edge) connecting two buses in the microgrid.
 *
 * Status thresholds:
 *  - `utilizationPct > 95`          → `'critical'`
 *  - `85 < utilizationPct <= 95`    → `'amber'`
 *  - otherwise                      → `'normal'`
 *
 * @property id             - Unique line identifier, e.g. `"LINE-01"`
 * @property from           - Source bus ID
 * @property to             - Destination bus ID
 * @property flowMW         - Current active power flow in MW
 * @property capacityMW     - Thermal rating (maximum flow) in MW
 * @property utilizationPct - |flowMW| / capacityMW × 100
 * @property status         - Congestion status based on utilization thresholds
 * @property ptdfRow        - Row of the PTDF matrix for this line (7 elements)
 */
export interface Line {
  /** Unique line identifier, e.g. `"LINE-01"`. */
  id: string;
  /** Source bus ID. */
  from: string;
  /** Destination bus ID. */
  to: string;
  /** Active power flow in MW. */
  flowMW: number;
  /** Thermal capacity (maximum allowable flow) in MW. */
  capacityMW: number;
  /** Utilization percentage: |flowMW| / capacityMW × 100. */
  utilizationPct: number;
  /**
   * Congestion status derived from `utilizationPct`.
   * - `'normal'`   : utilizationPct ≤ 85
   * - `'amber'`    : 85 < utilizationPct ≤ 95
   * - `'critical'` : utilizationPct > 95
   */
  status: 'normal' | 'amber' | 'critical';
  /** PTDF row vector for this line; one entry per bus (7 elements). */
  ptdfRow: number[];
}

/**
 * Complete snapshot of the microgrid state: buses, lines, and the PTDF matrix.
 *
 * PTDF (Power Transfer Distribution Factor) matrix: shape [9 lines × 7 buses].
 * Element PTDF[l][b] = fraction of a 1 MW injection at bus b that flows on line l.
 *
 * @property buses - Array of 7 bus objects
 * @property lines - Array of 9 line objects
 * @property ptdf  - [9 × 7] PTDF matrix
 */
export interface GridData {
  /** Array of 7 bus objects (BUS-01 … BUS-07). */
  buses: Bus[];
  /** Array of 9 transmission lines. */
  lines: Line[];
  /**
   * Power Transfer Distribution Factor matrix.
   * Dimensions: [9 lines × 7 buses].
   * PTDF[l][b] = sensitivity of line l flow to a 1 MW injection shift at bus b.
   */
  ptdf: number[][];
}

// ---------------------------------------------------------------------------
// Article / CMS types
// (used by lib/mock/articles.ts, /articles, /articles/[slug])
// ---------------------------------------------------------------------------

/**
 * A single section within an article's body, used for structured rendering.
 *
 * @property heading - Section heading text
 * @property content - Prose content; may include inline LaTeX-style notation
 *                     surrounded by backticks, e.g. `δ_ask(q) = base − …`
 */
export interface ArticleSection {
  /** Section heading text. */
  heading: string;
  /**
   * Prose content for this section.
   * Inline math notation uses backtick delimiters, e.g. `σ²γ / (2kA)`.
   */
  content: string;
}

/**
 * A research article in the Sovereign-AMM knowledge base.
 *
 * Category → badge colour mapping (bijection):
 *  - `'QUANT RESEARCH'`   → `'emerald'`
 *  - `'HARDWARE PHYSICS'` → `'amber'`
 *  - `'GRID PHYSICS'`     → `'sky'`
 *  - `'WHITE PAPER'`      → `'slate'`
 *  - `'APPLIED CRYPTO'`   → `'violet'`
 *
 * @property slug        - URL-safe identifier, e.g. `"glft-vs-avellaneda-stoikov"`
 * @property title       - Display title
 * @property category    - Research category (drives badge colour)
 * @property badgeColor  - Tailwind colour token for the category badge
 * @property publishedAt - ISO 8601 date string, e.g. `"2024-01-15"`
 * @property readTime    - Estimated reading time in minutes
 * @property summary     - One-paragraph summary used on listing cards
 * @property body        - Ordered array of prose sections
 * @property pullQuote   - Highlighted pull-quote rendered in the article detail view
 */
export interface Article {
  /** URL-safe slug, unique across all articles. */
  slug: string;
  /** Display title of the article. */
  title: string;
  /**
   * Research category.
   * Determines the `badgeColor` via the category→colour bijection.
   */
  category:
    | 'QUANT RESEARCH'
    | 'HARDWARE PHYSICS'
    | 'GRID PHYSICS'
    | 'WHITE PAPER'
    | 'APPLIED CRYPTO';
  /**
   * Tailwind colour token for the category badge.
   * Must match the category→colour bijection exactly.
   */
  badgeColor: 'emerald' | 'amber' | 'sky' | 'slate' | 'violet';
  /** ISO 8601 publication date string, e.g. `"2024-01-15"`. */
  publishedAt: string;
  /** Estimated reading time in minutes (integer). */
  readTime: number;
  /** One-paragraph summary used on article listing cards. */
  summary: string;
  /** Ordered body sections with headings and prose content. */
  body: ArticleSection[];
  /** Pull-quote highlighted in the article detail view. */
  pullQuote: string;
}

// ---------------------------------------------------------------------------
// RAG copilot types
// (used by lib/mock/rag.ts and components/landing/RagCopilot.tsx)
// ---------------------------------------------------------------------------

/**
 * Result returned by `matchQuery(query)` after simulated 600 ms latency.
 *
 * When `isFallback` is `true`, no keyword group matched and a generic
 * fallback answer is used.
 *
 * @property answer             - Main answer paragraph shown to the user
 * @property sources            - List of source document titles or URLs
 * @property suggestedQuestions - Follow-up questions to show as chips
 * @property isFallback         - `true` when no keyword group matched
 */
export interface RagResult {
  /** Main answer paragraph rendered in the RAG copilot panel. */
  answer: string;
  /**
   * Source references for this answer (document titles or short URLs).
   * Rendered as a bulleted list below the answer.
   */
  sources: string[];
  /**
   * Follow-up question suggestions rendered as clickable chips.
   * Clicking a chip pre-fills the query input.
   */
  suggestedQuestions: string[];
  /**
   * `true` when no keyword group matched the query and the fallback
   * answer was used instead. Components may render a subtle indicator.
   */
  isFallback: boolean;
}

// ---------------------------------------------------------------------------
// Store / UI types
// (used by lib/store.ts and AuthDrawer)
// ---------------------------------------------------------------------------

/**
 * The two possible modes for the AuthDrawer slide-in panel.
 *
 * - `'signin'`  – sign-in form shown by default
 * - `'signup'`  – sign-up / registration form shown
 */
export type AuthMode = 'signin' | 'signup';
